### PR TITLE
Added social media profile links.

### PR DESCRIPTION
**Pull request by arkaseth**

### CODE REVIEW

**Comment by arkaseth** [comment]
I had to do most by manual search. Some of them don't have any profiles on some social media platforms.

**Comment by monsij** [comment]
> I had to do most by manual search. Some of them don't have any profiles on some social media platforms.

yes, kindly complete all of them so that it is ready to be merged

**Comment by monsij** [comment]
Great work! Now squash both the commits with a commit message" Add profile links" . will be ready to merge thrn

**Comment by arkaseth** [comment]
Cannot seem to merge the commits.  git rebase -i HEAD~2 doesn't show the two commits of mine.

**Pull request closed without merging**
